name: readiculous_frontend
description: "Frontend for Readiculous Project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  go_router: ^17.0.1
  riverpod_annotation: ^4.0.1
  flutter_riverpod: ^3.2.0
  riverpod_lint: ^3.0.0-dev.4
  riverpod: ^3.2.0
  intl_utils: ^2.8.8
  mysql1: ^0.20.0
  dio: ^5.9.0
  google_fonts: ^7.1.0
  logger: ^2.6.2
  pretty_dio_logger: ^1.4.0
  flutter_asset_generator: ^1.2.0
  shared_preferences: ^2.5.4
  uuid: ^4.5.2
  flutter_vector_icons: ^2.0.0
  flutter_native_splash: ^2.4.6
  percent_indicator: ^4.2.5
  multi_select_flutter: ^4.1.3
#  flutter_localization: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  assets:
    - assets/images/


  # Remove the l10n configuration here
  # You don't need to define the l10n configuration manually in pubspec.yaml for the new intl package
flutter_intl:
  enabled: true
  main_locale: en
